server:
  port: 8081

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: D:\BasicMSA-Config

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://discUser:discPassword@localhost:8082/eureka/
      